In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df=pd.read_csv('diabetes.csv')

In [4]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000


In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
X= df.drop("Outcome", axis=1)
y= df["Outcome"]

In [8]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
lr = LinearRegression()
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

In [11]:
lr_pred

array([ 0.33550028,  0.23809869,  0.1510522 ,  0.2401365 ,  0.48142376,
        0.45257375, -0.17450469,  0.60662287,  0.52417796,  0.70476953,
        0.32360466,  0.85290601,  0.38466612,  0.36056948,  0.09946712,
        0.41539557,  0.17869123,  0.07782301,  0.80730861,  0.51299477,
        0.28090594,  0.08303057,  0.5099157 ,  0.11381771,  0.51325022,
        0.82528549,  0.17892718, -0.0594202 ,  0.28338572,  0.16407949,
        0.83851225,  0.80737515,  0.68154389,  0.7649502 ,  0.56140297,
        0.62123131,  1.06134554,  0.30990775,  0.51752336,  0.63691482,
        0.07075333,  0.57757007,  0.55015462,  0.37541745, -0.07644182,
        0.50119208,  0.59600162,  0.27464761,  0.42477995,  0.9941898 ,
        0.00969584,  0.61763578,  0.73395288,  0.31090975,  0.13456812,
       -0.02536316,  0.71219147, -0.30518218,  0.41994556,  0.67869594,
        0.66891428,  0.3798452 ,  0.2956646 ,  0.288035  ,  0.06813053,
        0.55464338,  0.01368504,  0.6272007 , -0.02033281,  0.63

In [12]:
ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

ridge_pred = ridge.predict(X_test)

In [13]:
ridge_pred

array([ 0.33562553,  0.23865432,  0.15141191,  0.23927604,  0.48175372,
        0.45291268, -0.17439738,  0.60581669,  0.52451803,  0.70517659,
        0.32408837,  0.85358458,  0.38533332,  0.35963968,  0.09890582,
        0.4147291 ,  0.17900707,  0.07793044,  0.80775775,  0.51318737,
        0.28128703,  0.08319576,  0.5104758 ,  0.11411038,  0.5135954 ,
        0.82563256,  0.17930315, -0.05900606,  0.28403935,  0.16387146,
        0.838375  ,  0.80730606,  0.68215629,  0.76435945,  0.56071815,
        0.62063045,  1.0617774 ,  0.30930806,  0.51780251,  0.63723082,
        0.07093451,  0.57718993,  0.55006988,  0.37519129, -0.07623272,
        0.50073821,  0.59467635,  0.27479884,  0.4240089 ,  0.99337792,
        0.01011664,  0.61725011,  0.73406386,  0.31067451,  0.13503486,
       -0.0251524 ,  0.71262437, -0.30498261,  0.41932968,  0.67923258,
        0.66904401,  0.38009386,  0.29547587,  0.2871326 ,  0.06854522,
        0.55504187,  0.01388339,  0.62754813, -0.02070239,  0.63

In [14]:
lasso = Lasso(alpha=0.01)
lasso.fit(X_train, y_train)

lasso_pred = lasso.predict(X_test)

In [15]:
lasso_pred

array([ 0.33949549,  0.26928486,  0.17277395,  0.19052809,  0.49996942,
        0.46960679, -0.16598622,  0.56149309,  0.54305657,  0.7289604 ,
        0.34498391,  0.88959149,  0.42130065,  0.30815963,  0.06860271,
        0.3783916 ,  0.19551033,  0.08196512,  0.82854611,  0.52494859,
        0.30328662,  0.09499572,  0.53041661,  0.13143877,  0.52632134,
        0.84139849,  0.19721237, -0.03138088,  0.3196902 ,  0.15430671,
        0.82976012,  0.80537319,  0.71481588,  0.73121469,  0.52675988,
        0.58234225,  1.08418296,  0.28092023,  0.52782498,  0.6521007 ,
        0.08007892,  0.56095186,  0.54492999,  0.3550072 , -0.06312069,
        0.47650395,  0.52153716,  0.28010957,  0.38099918,  0.95223005,
        0.03280304,  0.5930764 ,  0.73279179,  0.30015067,  0.16511297,
       -0.01351424,  0.73770188, -0.29326414,  0.38524673,  0.70795086,
        0.67226735,  0.39391179,  0.28892444,  0.23146449,  0.09413731,
        0.577719  ,  0.02579444,  0.64651694, -0.03440069,  0.63

In [20]:
def evaluate(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    
    print(f"Mean Absolute Error: {mae}")
    print(f"Root Mean Square Error: {rmse}")
    print(f"R-squared: {r2}")

In [21]:
evaluate(y_test, lr_pred)

Mean Absolute Error: 0.34812825999928226
Root Mean Square Error: 0.4135761995189049
R-squared: 0.25500281176741757


In [22]:
evaluate(y_test, ridge_pred)

Mean Absolute Error: 0.34818263276153066
Root Mean Square Error: 0.413648738686097
R-squared: 0.2547414513943689


In [23]:
evaluate(y_test, lasso_pred)

Mean Absolute Error: 0.3517089171774846
Root Mean Square Error: 0.41897985164094875
R-squared: 0.2354078499579998


In [24]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Ridge Regression", "Lasso Regression"],
    "MAE": [
        mean_absolute_error(y_test, lr_pred),
        mean_absolute_error(y_test, ridge_pred),
        mean_absolute_error(y_test, lasso_pred)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, lr_pred)),
        np.sqrt(mean_squared_error(y_test, ridge_pred)),
        np.sqrt(mean_squared_error(y_test, lasso_pred))
    ],
    "R2": [
        r2_score(y_test, lr_pred),
        r2_score(y_test, ridge_pred),
        r2_score(y_test, lasso_pred)
    ]
})

print(results)

               Model       MAE      RMSE        R2
0  Linear Regression  0.348128  0.413576  0.255003
1   Ridge Regression  0.348183  0.413649  0.254741
2   Lasso Regression  0.351709  0.418980  0.235408


In [ ]:
1. Which model performs best?
Ridge regression performs best with the lowest MAE and RMSE, and the highest R² score.



In [ ]:
2. Why does Ridge reduce overfitting?
Ridge regression adds a penalty term to the loss function that shrinks the coefficients of less important features towards zero. This helps to prevent overfitting by reducing the models complexity and making it less sensitive to noise in the training data.

In [ ]:
3. Which features were removed  Lasso?
Lasso removes features by making their coefficient exactly zero.
In this dataset:
No feature was completely removed (coefficients very small but not zero)
If α increases, Lasso may remove features like:
SkinThickness
Insulin
BloodPressure